spring.application.name=MqttRestApp
server.port=8081

# Kafka Configuration for Docker
spring.kafka.bootstrap-servers=kafka:29092
spring.kafka.consumer.group-id=tracking-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Kafka Topics
kafka.topic.sensor-data=sensor-data

# MQTT Configuration for Docker
mqtt.broker.url=tcp://mosquitto:1883
mqtt.broker.username=oussama
mqtt.broker.password=123456
mqtt.client.id=springbootClient

# SSL truststore
javax.net.ssl.trustStore=classpath:truststore.jks
javax.net.ssl.trustStorePassword=123456

# Replace "my-realm" with your Keycloak realm name.
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8080/realms/parcel-tracking-auth

# This is the "registration" section. It defines your specific application.
# The "keycloak" part matches the provider name above.
spring.security.oauth2.client.registration.keycloak.client-id=springclient
spring.security.oauth2.client.registration.keycloak.client-secret=3NM0HHKFeGLdikolptNugKyLfNhjwIVh
spring.security.oauth2.client.registration.keycloak.redirect-uri=http://localhost:8081/login/oauth2/code/keycloak
spring.security.oauth2.client.registration.keycloak.scope=openid, profile, email
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code