spring:
  application:
    name: SensorsPayload
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 1440
mqtt:
  broker: ssl://192.168.100.253:8883
  clientId: springClient
  username: oussama
  password: 123456
  topics:
    - sensor/dht11
    - sensor/gps
  tls:
    truststore: classpath:truststore.jks
    truststorePassword: changeit
  ca-cert-path: classpath:ca.crt
